[project]
name = "dejavue"
version = "0.1.0"
description = "Fullstack one app boilerplate"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.7",
    "django-vite>=3.1.0",
    "inertia-django>=1.2.0",
    "whitenoise>=6.11.0",
]
